import type { Metadata } from "next";
import { Space_Grotesk, Fira_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from "@/components/providers";

const spaceGrotesk = Space_Grotesk({
	variable: "--font-space-grotesk",
	subsets: ["latin"],
});

const firaSans = Fira_Sans({
	variable: "--font-fira-sans",
	subsets: ["latin"],
	weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${spaceGrotesk.variable} ${firaSans.variable} antialiased`}
			>
				<Providers>
					<div>
						{children}
						<Toaster />
					</div>
				</Providers>
			</body>
		</html>
	);
}
